#!/bin/sh /etc/rc.common
# Copyright (C) 2024 Maizil41

START=99

start() {
    echo "Starting BOT"
    python3 /usr/bin/telebot.py > /var/log/telebot.log 2>&1 &
}

stop() {
    echo "Stopping BOT"
    killall python3
}

restart() {
    stop
    sleep 1
    start
}

